name: 'CodeAsk CLI CI'
description: '运行codeask-cli生成代码说明'
author: 'shadow3aaa'

inputs:
  working-directory:
    description: '执行codeask-cli的工作目录'
    required: false
    default: '.'
  openai_api_key:
    description: "OpenAI API key"
    required: false
  anthropic_api_key:
    description: "Anthropic Claude API key"
    required: false
  azure_openai_api_key:
    description: "Azure OpenAI API key"
    required: false
  gemini_api_key:
    description: "Google Gemini API key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install codeaskcli from PyPI
      uses: threeal/pipx-install-action@v1.0.0
      with:
        packages: codeaskcli

    - name: Run codeaskcli
      shell: bash
      run: |
        cd "${{ inputs.working-directory }}"
        export OPENAI_API_KEY="${{ inputs.openai_api_key }}"
        export ANTHROPIC_API_KEY="${{ inputs.anthropic_api_key }}"
        export AZURE_OPENAI_API_KEY="${{ inputs.azure_openai_api_key }}"
        export GEMINI_API_KEY="${{ inputs.gemini_api_key }}"
        codeaskcli
